<template>
    <!-- Calendar -->
    <div class="calendar" data-calendar>
        <!-- Date Range -->
        <div class="calendar__range" data-range-carousel>
            <!-- Range List -->
            <ul class="calendar__range-list" data-carousel>
               <!-- Added Via JS -->
            </ul>
            <!-- / Range List -->
            <!-- Carousel Arrows -->
            <div class="calendar__range-arrows">
                <button class="calendar__range-arrows-item" data-carousel-prev :aria-label="$t('components.calendar.calendar.data-carousel-prev')">
                     <svg xmlns="http://www.w3.org/2000/svg" class="calendar__range-arrows-item-icon">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/images/sprites/sprites.svg#chevron-left"></use>
                    </svg>
                </button>

                <button class="calendar__range-arrows-item" data-carousel-next :aria-label="$t('components.calendar.calendar.data-carousel-next')">
                     <svg xmlns="http://www.w3.org/2000/svg" class="calendar__range-arrows-item-icon">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/assets/images/sprites/sprites.svg#chevron-right"></use>
                    </svg>
                </button>
            </div>
            <!-- / Carousel Arrows -->   
        </div>
        <!-- / Date Range -->
        <!-- Calendar Days -->
        <div class="calendar__days">
            <!-- Days List -->
            <ul class="calendar__days-list" data-calendar-days>
                <!-- Generated By JS -->
            </ul>
            <!-- / Days List -->
        </div>
        <!-- / Calendar Days -->
        <!-- Container -->
        <div class="calendar__container" data-calendar-view>
            <!-- Generated By JS -->
        </div>
        <!-- / Container -->
    </div>
    <!-- / Calendar -->
</template>

<script>
/* Dependencies */
import { Calendar } from "../../../core/objects/Calendar";
import { Loading } from "../../../core/objects/Loading";

import { checkCache } from "../../../core/helpers/checkCache";
import { createBlockContent } from "../../../core/helpers/calendar/createBlockContent";
import { initCalendar } from "../../../core/implementation/calendar/initCalendar";
import serviceBus from '../../services/serviceBus';

// Placeholder for loader
let loader;

export default {
    data() {
        return {
            activeMonth: undefined,
            calendar: undefined,
            range: undefined,
            validCache: false
        }
    },

    created() {
        // Check the cached data
        this.validCache = checkCache(this.$store.getters.getCalendarCache, 5);

        // If the cache is not valid
        if(!this.validCache) {
            // Retrieve the calendar data
            serviceBus.$emit("fetchCalendar");
        }
    },

    computed: {
        // Load calendar data from state
        calendarData() {
            return this.$store.getters.getCalendarData;
        }
    },

    methods: {
        // Handle event selection
        selectEvent(item) {
            serviceBus.$emit("showsSetChosenShow", {item, callback: () => {
                this.$router.push({name: "seatSelect"});
            }});
        },
        
        // Initiate the calendar
        initiateCalendar() {
            initCalendar(this, () => {
                loader.remove();
            });
        }
    },
    mounted() {

        // Created an instance of the calendar
        this.calendar = new Calendar(this.$el)

        // Register the render content function
        this.calendar.renderBlockContents = createBlockContent;

        // Register the handle select function
        this.calendar.selectCalendarItem = this.selectEvent;

        // Create a new loader
        loader = new Loading(this.$el.parentNode, {
            title: this.$t('components.calendar.calendar.loader.title'),
            icon: "calendar"
        });

        loader.insert();

        // If the cache is valid
        if(this.validCache) {
            this.initiateCalendar();
        }
    },

    watch: {
        
        // Watch calendar data for definition
        calendarData() {
            // Check if the calendar data is not undefined
            if(this.calendarData !== undefined) {
                // Initiate Calendar
                this.initiateCalendar();
            }
        }, 
        
        // Watch active month & update calendar to match 
        activeMonth() {
            
            // Set the active month
            this.calendar.setMonth({
                month: this.activeMonth.details.month,
                year: this.activeMonth.details.year
            });

            // Remove the old active month
            const currentActiveRange = this.range.filter((currentMonth) => currentMonth.element.getAttribute("data-active") !== null);
            
            // If there is an acive item
            if(currentActiveRange.length > 0) {
                // Remove the active item
                currentActiveRange[0].element.removeAttribute("data-active");
            }

            // Update the active month
            this.activeMonth.element.setAttribute("data-active", "");
        }
    }
}
</script>
